
###
# FETCH TARGET
GET http://localhost:4004/bonus/Target
###
# FETCH BONUS
GET http://localhost:4004/bonus/Bonus
###
# create bonus
POST http://localhost:4004/bonus/createbonus
Content-Type: application/json

{
    "name": "Siera",
    "location": "NIARAI WONDERLAND",
    "status": "running",
    "beginDate": "2023-12-07",
    "endDate": "2024-04-07",
    "description": "HAMABNA BONO NULAND",
    "trancheWeight": 65,
    "target": [
        {
            "name": "HEALTH TARGET",
            "weight": 60,
            "achievement": 100
        },
        {
            "name": "QUEEN TARGET",
            "weight": 10,
            "achievement": 100
        },
        {
            "name": "SONIPER TARGET",
            "weight": 30,
            "achievement": 100
        }
    ]
}
###
# edit bonus
POST http://localhost:4004/bonus/editbonus
Content-Type: application/json

{
    "id": "1cdd1600-4aa3-4343-981c-7a0bca08f6d6",
    "name": "ASTHOROS BOB SQUARE BONUS",
    "location": "TOGO WONDERLAND",
    "status": "completed",
    "beginDate": "2024-03-07",
    "endDate": "2025-01-07",
    "description": "HAMABNA BONO NULAND",
    "trancheWeight": 46,
    "target": [
        {
            "name": "DIET TARGET",
            "weight": 90,
            "achievement": 70
        },
        {
            "name": "KING TARGET",
            "weight": 90,
            "achievement": 10
        },
        {
            "name": "GUNNER TARGET",
            "weight": 90,
            "achievement": 110
        }
    ]
}

###
# delete bonus
POST http://localhost:4004/bonus/deletebonus
Content-Type: application/json

{
    "id": "954a5cf2-9089-4465-b876-986e2340370f"
}
###
# lock bonus
POST http://localhost:4004/bonus/lockbonus
Content-Type: application/json

{
    "id": "de9de85c-84fc-41f1-958d-89305e549655"
}
###
# exclude paticipants
POST http://localhost:4004/bonus/exclude
Content-Type: application/json

{
    "id": "0050ef4f-f251-4814-a5c9-e089f7666a35"
}
###
# override payout
POST http://localhost:4004/bonus/override
Content-Type: application/json

{
    "id": "0050ef4f-f251-4814-a5c9-e089f7666a35",
    "amount": 70000,
    "justification": "Too fat for that amount"
}
###
# FETCH participants
GET http://localhost:4004/bonus/Participant
###
# create participants
POST http://localhost:4004/bonus/Participant
Content-Type: application/json

{
    "localId": "c89d4d05-d1ea-4ce0-bbf6-1582292b68a9",
    "name": "HAN WILVOCK",
    "department": "Sale",
    "bonus": "iuouioupouipoiu",
    "status": "running",
    "location": "NEW JERSEY",
    "startDate": "2023-11-02",
    "endDate": "2022-09-01",
    "weight": 90.0,
    "calculated_amount": 56.90,
    "final_amount": 90.67,
    "excluded": false,
    "justification": "IS FAT"
}

###
# create Target
POST http://localhost:4004/bonus/Target
Content-Type: application/json

{
    "name": "HEALTH TARGET-1",
    "weight": 90,
    "achievement": 70
}

###
# FETCH Targets
GET http://localhost:4004/bonus/Target



